# 生产环境配置
# 生产环境特定的配置覆盖

# 服务器配置 - 生产环境优化
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  compression:
    enabled: ${COMPRESSION_ENABLED:true}
  # 生产环境错误处理
  error:
    include-stacktrace: never
    include-message: never
    whitelabel:
      enabled: false

# Spring配置
spring:
  # 数据库配置 - 生产环境使用外部数据库
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/proddb}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  # JPA配置 - 生产环境严格模式
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}  # 生产环境只验证不修改
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # 生产环境禁用H2控制台
  h2:
    console:
      enabled: false

# 日志配置 - 生产环境精简日志
logging:
  level:
    root: WARN
    com.company: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:/var/log/app/application.log}
    max-size: 100MB
    max-history: 30
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# 安全配置 - 生产环境严格设置
security:
  jwt:
    secret: ${JWT_SECRET}  # 必须通过环境变量提供
    expiration: ${JWT_EXPIRATION:86400}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}  # 必须明确指定
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type
    allow-credentials: false  # 生产环境关闭凭据
  rate-limit:
    requests-per-minute: ${RATE_LIMIT:60}  # 生产环境严格限流

# 管理端点 - 生产环境限制访问
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  security:
    enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true

# 自定义配置 - 生产环境设置
app:
  config:
    cache:
      ttl: ${CACHE_TTL:600}  # 生产环境长缓存时间
      max-size: ${CACHE_MAX_SIZE:10000}
    monitoring:
      enabled: true
      interval: ${MONITORING_INTERVAL:300}  # 生产环境较低频率监控
    audit:
      enabled: true
      retention-days: ${AUDIT_RETENTION_DAYS:90}  # 生产环境长保留期
    hotreload:
      enabled: false  # 生产环境禁用热更新
    encryption:
      enabled: true
      algorithm: AES-256-GCM
      key-rotation-days: 30

# 生产环境特定配置
prod:
  security:
    ssl:
      enabled: ${SSL_ENABLED:true}
    headers:
      frame-options: DENY
      content-type-options: nosniff
      xss-protection: "1; mode=block"
    session:
      timeout: 1800  # 30分钟会话超时
  monitoring:
    alerts:
      enabled: true
    metrics:
      jvm: true
      system: true
      database: true
  backup:
    enabled: true
    schedule: "0 2 * * *"  # 每天凌晨2点备份
    retention-days: 30